sudo: required
services:
  - docker

before_install:
  - docker build -t cuddlemuffin007/docker-react -f Dockerfile.dev .

script:
  - docker run cuddlemuffin007/docker-react npm run test -- --coverage
